
with open("students.txt", "w") as file:
    file.write("Lida\n")
    file.write("Tara\n")
    file.write("Allessandro\n")
    file.write("Rafael\n")
    file.write("Oli\n")
    file.write("Letlotlo\n")
    file.write("Ben\n")
    file.write("Maisie\n")
    file.write("Ollie\n")
    file.write("Harry\n")
    file.write("Ken\n")
    file.write("Bayne\n")
    file.write("Leila\n")
    file.write("Amelia\n")
    file.write("Selma\n")
    file.write("Amelia\n")
    file.write("Sofi\n")
    file.write("Tao\n")
    file.write("Marlee\n")
    file.write("Layla\n")
    file.write("Jolie\n")
    file.write("Aaron\n")
    file.write("Bram\n")
    file.write("Joseph\n")
    file.write("Bella\n")
    file.write("Axel\n")
with open("students.txt", "r") as file:
    for line in file:
        print(line.strip())
        print(line[1])